version: '3.7'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - api
      - db
    links:
      - api
    environment:
      API_HOST: api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo
    hostname: mongo
    restart: always
    ports:
      - '27017:27017'
