version: '3.7'

services:
  db:
    image: mongo
    networks: 
      - backend
    volumes:
      - mongo-data:/data/db
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - '4000:4000'
    depends_on:
      - db
    links:
      - db
    environment:
      - MONGO_URL=db
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - api
      - db
    links:
      - api
    environment:
      - NODE_ENV='production'
      - API_URL='http://api:4000/',
volumes:
  mongo-data:
networks:
  backend: