version: '3.7'

services:
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - './api/src:/app/src'
    ports:
      - '4000:4000'
    depends_on:
      - db
