version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - './api/src:/app/src'
    ports:
      - '4000:4000'
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo
    hostname: mongo
    restart: always
    ports:
      - '27017:27017'
